server:
  port: 8888



spring:
  datasource:
    url: jdbc:mysql://192.168.1.16:3306/bjpowernode?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver

logging:
  level:
    org.example: debug